import clsx from 'clsx';
import Head from "next/head";
import { useMoralis } from "react-moralis";
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";
import mainLogo from '../public/logo.png'
import Image from 'next/image'

export default function Home() {
  const { Moralis } = useMoralis();
  async function login() {
    await Moralis.Web3.enableWeb3();
    await Moralis.Web3.authenticate();
    console.log(Moralis.User.current().get("ethAddress"));
  }
  const particlesInit = async (main) => {
    console.log(main);

    // you can initialize the tsParticles instance (main) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(main);
  };

  const particlesLoaded = (container) => {
    console.log(container);
  };

  return (
    <div>
      <Head>
        <title>Adashe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        className={clsx(
          'align-center fixed top-0 z-40 flex h-header-sm w-full px-4 text-white',
          'md:px-8',
          'lg:h-header-lg',
        )}
        role="banner"
      >

        <Image
          src={mainLogo}
          alt="Logo"
          quality="85"
          layout="intrinsic"
        />

        {/* Country selector + Cart toggle */}
        <div
          className={clsx(
            'absolute right-0 flex h-full items-center', //
            'md:mr-4',
          )}
        >
          
          <div
            className={clsx(
              'hidden', //
              'lg:block',
            )}
          >
            
          </div>
          <div className="flex h-full items-center justify-center py-0 pr-4 pl-2">
            <button onClick={login}>Login</button>
          </div>
        </div>
      </header>
      <main>
        <Particles
          id="tsparticles"
          init={particlesInit}
          loaded={particlesLoaded}
          options={{
            background: {
              color: {
                value: "#000000",
              },
            },
            fpsLimit: 120,
            interactivity: {
              events: {
                onClick: {
                  enable: true,
                  mode: "push",
                },
                onHover: {
                  enable: true,
                  mode: "repulse",
                },
                resize: true,
              },
              modes: {
                push: {
                  quantity: 4,
                },
                repulse: {
                  distance: 200,
                  duration: 0.4,
                },
              },
            },
            particles: {
              color: {
                value: "#382C53",
              },
              links: {
                color: "#382C53",
                distance: 150,
                enable: true,
                opacity: 1.0,
                width: 1,
              },
              collisions: {
                enable: true,
              },
              move: {
                direction: "none",
                enable: true,
                outModes: {
                  default: "bounce",
                },
                random: false,
                speed: 0.8,
                straight: false,
              },
              number: {
                density: {
                  enable: true,
                  area: 1920,
                },
                value: 80,
              },
              opacity: {
                value: 1.0,
              },
              shape: {
                type: "circle",
              },
              size: {
                value: { min: 1, max: 5 },
              },
            },
            detectRetina: true,
          }}
        />


      </main>
    </div>
  );
}
